# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='\u59d3\u540d')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('address', models.CharField(max_length=100, verbose_name='\u8054\u7cfb\u5730\u5740')),
                ('message', models.CharField(max_length=500, verbose_name='\u7559\u8a00\u4fe1\u606f')),
                ('message_time', models.DateTimeField(auto_now=True, verbose_name='\u7559\u8a00\u65f6\u95f4')),
            ],
            options={
                'managed': True,
                'ordering': ['id'],
                'verbose_name_plural': '\u7559\u8a00\u677f\u6570\u636e\u8868',
                'db_table': 'messages',
                'verbose_name': '\u7559\u8a00\u677f\u6570\u636e\u8868',
            },
        ),
    ]
